name: Android CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run unit tests
      run: ./gradlew test --stacktrace

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/test-results/

  build:
    name: Build APK and AAR
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    - name: Build library AAR
      run: ./gradlew :WheelViewLib:assembleRelease
      
    - name: Build sample APK
      run: ./gradlew :WheelViewSample:assembleDebug

    - name: Upload library AAR
      uses: actions/upload-artifact@v4
      with:
        name: wheelview-library
        path: WheelViewLib/build/outputs/aar/*.aar

    - name: Upload sample APK
      uses: actions/upload-artifact@v4
      with:
        name: wheelview-sample-apk
        path: WheelViewSample/build/outputs/apk/debug/*.apk

  lint:
    name: Run Android Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Android Lint
      run: ./gradlew lint --stacktrace

    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: |
          **/build/reports/lint-results-*.html
          **/build/reports/lint-results-*.xml