name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Grant execute permission for validation script
      run: chmod +x scripts/validate.sh

    - name: Validate 2025 compatibility
      run: ./scripts/validate.sh

    - name: Validate Gradle Wrapper
      run: ./gradlew wrapper --gradle-version=8.5

    - name: Build library
      run: ./gradlew :WheelViewLib:build

    - name: Build sample APK
      run: ./gradlew :WheelViewSample:assembleDebug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: |
          WheelViewSample/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          WheelViewLib/build/reports/tests/
          WheelViewSample/build/reports/tests/
        retention-days: 30

    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: |
          **/build/reports/lint*.html
          **/build/reports/lint*.xml
        retention-days: 30